apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{include "cloudwatch-exporter.fullname" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{include "cloudwatch-exporter.fullname" .}}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudwatch-exporter.serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
