apiVersion: v1
kind: Service
metadata:
  name: {{ include "rds-exporter.fullname" . }}
  labels:
  {{- include "rds-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "rds-exporter.selectorLabels" . | nindent 4 }}
