apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-metastore.name" . }}-config
  labels:
  {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
data:
  metastore-site.xml: |
    <configuration>
    <property>
    <name>javax.jdo.option.ConnectionURL</name>
    <value>{{.Values.database.jdbc}}</value>
    </property>
    <property>
    <name>javax.jdo.option.ConnectionDriverName</name>
    <value>{{.Values.database.driver}}</value>
    </property>
    <property>
    <name>javax.jdo.option.ConnectionUserName</name>
    <value>{{.Values.database.username}}</value>
    </property>
    <property>
    <name> javax.jdo.option.ConnectionPassword</name>
    <value>{{.Values.database.password}}</value>
    </property>
    <property>
    <name>metastore.expression.proxy</name>
    <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
    </property>
    <property>
    <name>metastore.task.threads.always</name>
    <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask,org.apache.hadoop.hive.metastore.MaterializationsCacheCleanerTask</value>
    </property>
    <property>
    <name>datanucleus.autoCreateSchema</name>
    <value>false</value>
    </property>
    <property>
    <name>hive.metastore.uris</name>
    <value>thrift://localhost:9083</value>
    </property>
    <property>
    <name>hive.metastore.warehouse.dir</name>
    <value>file:///tmp/</value>
    </property>
    <property>
    <name>datanucleus.schema.autoCreateAlltrue</name>
    <value>true</value>
    </property>
    <property>
    <name>hive.metastore.event.db.notification.api.authfalse</name>
    <value>false</value>
    </property>
    <property>
    <name>hadoop.proxyuser.hive.hosts</name>
    <value>HS2_HOST</value>
    </property>
    <property>
    <name>hadoop.proxyuser.hive.groups*</name>
    <value>*</value>
    </property>
    <property>
    <name>datanucleus.autoStartMechanism</name>
    <value>SchemaTable</value>
    </property>

    {{- range $k, $v := .Values.hive.config }}
    <property>
    <name>{{$k}}</name>
    <value>{{$v}}</value>
    </property>
    {{- end }}
    </configuration>

