apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hive-metastore.name" . }}
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "hive-metastore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hive-metastore.labels" $ | trim | nindent 8 }}
        {{- include "hive-metastore.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: hive-metastore-config
          configMap:
            name: {{ include "hive-metastore.name" . }}-config

      containers:
        - name: {{ .Chart.Name }}
          image: "{{.Values.image.name}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/hive-metastore/bin/entrypoint.sh"]
          ports:
            - name: tcp
              containerPort: 9083
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9083
          readinessProbe:
            tcpSocket:
              port: 9083
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/hive-metastore/conf/metastore-site.xml
              subPath: metastore-site.xml
              name: hive-metastore-config
