{{ if .Values.exchange.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.exchange-manager" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: exchange-manager
data:
  exchange-manager.properties: |-
    exchange-manager.name="filesystem"
    exchange.base-directories={{ .Values.exchange.aws.base_directories }}
    exchange.s3.region={{ .Values.exchange.aws.region }}
    exchange.s3.aws-access-key={{ .Values.exchange.aws.access_key }}
    exchange.s3.aws-secret-key={{ .Values.exchange.aws.secret_key }}

{{ end }}