{{ if .Values.exporters.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.jmx-exporter" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: exporter
data:
  {{- with .Values.exporters.jmx.config }}
  config.yml: |-
    {{- toYaml . | nindent 4 }}
    {{end}}
  {{end}}
---
