apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.connectors" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: connectors
data:
{{- with .Values.server.connectors }}
{{ toYaml . | indent 2 }}
{{end}}
