apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.fullname" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "trino.name" . }}
    release: {{ .Release.Name }}
    component: coordinator
---
  {{ if .Values.exporters.jmx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.fullname" . }}-jmx
  labels:
    app: {{ template "trino.name" . }}
    monitoring.service: jmx
    release: {{ .Release.Name }}
    chart: {{ template "trino.chart" . }}
    heritage: {{ .Release.Service }}
  {{- if .Values.service.labels }}
  {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.exporters.jmx.port }}
      targetPort: prom-exporter
      protocol: TCP
      name: exporter
  selector:
    app: {{ template "trino.name" . }}
    release: {{ .Release.Name }}
  {{end}}
---
