image:
  repository: prestosql/presto
  tag: 329
  pullPolicy: IfNotPresent
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000


presto:
  query:
    maxMemory: "4GB"
    maxMemoryPerNode: "1GB"

  coordinator:
    config:
      path: /usr/lib/presto/etc
      server:
        port: 8080
        loglevel: "INFO"
      jvm:
        maxHeapSize: "8G"
        gcMethod:
          type: "UseG1GC"
          g1:
            heapRegionSize: "32M"
      node:
        environment: production
        dataDir: /data/presto
        pluginDir: /usr/lib/presto/plugin

    resources: { }

    nodeSelector: { }

    tolerations: [ ]

    affinity: { }

  worker:
    replicas: 2
    config:
      path: /usr/lib/presto/etc
      server:
        port: 8080
        loglevel: "INFO"
      jvm:
        maxHeapSize: "8G"
        gcMethod:
          type: "UseG1GC"
          g1:
            heapRegionSize: "32M"
      node:
        environment: production
        dataDir: /data/presto
        pluginDir: /usr/lib/presto/plugin

    resources: { }

    nodeSelector: { }

    tolerations: [ ]

    affinity: { }
#server:
#  workers: 2
#  node:
#    environment: production
#    dataDir: /data/presto
#    pluginDir: /usr/lib/presto/plugin
#  log:
#    presto:
#      level: INFO
#  config:
#    path: /usr/lib/presto/etc
#    http:
#      port: 8080
#    query:
#      maxMemory: "4GB"
#      maxMemoryPerNode: "1GB"
#  jvm:
#    maxHeapSize: "8G"
#    gcMethod:
#      type: "UseG1GC"
#      g1:
#        heapRegionSize: "32M"
#
#
service:
  type: ClusterIP
