image:
  repository: prestosql/presto
  tag: 345
  pullPolicy: IfNotPresent
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000


presto:
  query:
    maxMemory: "4GB"
    maxMemoryPerNode: "1GB"

  coordinator:
    config:
      path: /usr/lib/presto/etc
      server:
        port: 8080
        loglevel: "INFO"
      jvm:
        maxHeapSize: "8G"
        gcMethod:
          type: "UseG1GC"
          g1:
            heapRegionSize: "32M"
      node:
        environment: production
        dataDir: /data/presto
        pluginDir: /usr/lib/presto/plugin

    resources: { }

    nodeSelector: { }

    tolerations: [ ]

    affinity: { }

  worker:
    replicas: 2
    config:
      path: /usr/lib/presto/etc
      gracefulShutdown:
        enabled: true
        gracePeriodSeconds: 300
      server:
        port: 8080
        loglevel: "INFO"
      jvm:
        maxHeapSize: "8G"
        gcMethod:
          type: "UseG1GC"
          g1:
            heapRegionSize: "32M"
      node:
        environment: production
        dataDir: /data/presto
        pluginDir: /usr/lib/presto/plugin

    resources: { }

    nodeSelector: { }

    tolerations: [ ]

    affinity: { }

  connectors:
    memory.properties: |-
      connector.name=memory

    tpcds.properties: |-
      connector.name=tpcds
      tpcds.splits-per-node=4

service:
  type: ClusterIP
