apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.coordinator" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
data:
  node.properties: |
    node.environment={{ .Values.presto.coordinator.config.node.environment }}
    node.data-dir={{ .Values.presto.coordinator.config.node.dataDir }}
    plugin.dir={{ .Values.presto.coordinator.config.node.pluginDir }}

  jvm.config: |
    -server
    -Xmx{{ .Values.presto.coordinator.config.jvm.maxHeapSize }}
    -XX:+{{ .Values.presto.coordinator.config.jvm.gcMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.presto.coordinator.config.jvm.gcMethod.g1.heapRegionSize }}
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true

  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port={{ .Values.presto.coordinator.config.server.port }}
    query.max-memory={{ .Values.presto.query.maxMemory }}
    query.max-memory-per-node={{ .Values.presto.query.maxMemoryPerNode }}
    discovery-server.enabled=true
    discovery.uri=http://localhost:{{ .Values.presto.coordinator.config.server.port }}

  log.properties: |
    io.prestosql={{ .Values.presto.coordinator.config.server.loglevel }}

---
