apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.connectors" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: connectors
data:
{{- with .Values.presto.connectors }}
{{ toYaml . | indent 2 }}
{{end}}
