apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "presto.coordinator" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
    {{ if .Values.exporters.jmx.enabled }}
    monitoring.jmx: enabled
    {{ end }}
spec:
  selector:
    matchLabels:
      app: {{ template "presto.name" . }}
      release: {{ .Release.Name }}
      component: coordinator
  template:
    metadata:
      labels:
        app: {{ template "presto.name" . }}
        release: {{ .Release.Name }}
        component: coordinator
    spec:
      {{- with .Values.image.securityContext }}
      securityContext:
        runAsUser: {{ .runAsUser }}
        runAsGroup: {{ .runAsGroup }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "presto.coordinator" . }}
        - name: connectors-config-volume
          configMap:
            name: {{ template "presto.connectors" . }}
        {{ if .Values.exporters.jmx.enabled }}
        - name: config-jmx-exporter
          configMap:
            name: {{ template "presto.jmx-exporter" . }}
        {{ end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.presto.coordinator.config.path }}
              name: config-volume
            - mountPath: {{ .Values.presto.coordinator.config.path }}/catalog
              name: connectors-config-volume
          ports:
            - name: http-coord
              containerPort: {{ .Values.presto.coordinator.config.server.port }}
              protocol: TCP
            {{ if .Values.exporters.jmx.enabled }}
            - name: jmx
              containerPort: {{ .Values.presto.config.jmx.registryPort }}
              protocol: TCP
            {{ end }}
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /ui/login.html
              port: http-coord
          readinessProbe:
            httpGet:
              path: /ui/login.html
              port: http-coord
          resources:
      {{- toYaml .Values.presto.coordinator.resources | nindent 12 }}


        {{ if .Values.exporters.jmx.enabled }}
        - name: jmx-exporter
          image: "{{ .Values.exporters.jmx.image.repository }}:{{ .Values.exporters.jmx.image.tag }}"
          imagePullPolicy: {{ .Values.exporters.jmx.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.exporters.jmx.port }}
              protocol: TCP
              name: prom-exporter
          livenessProbe:
            httpGet:
              path: /metrics
              port: prom-exporter
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 60
            failureThreshold: 8
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /metrics
              port: prom-exporter
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 60
            failureThreshold: 8
            successThreshold: 1
          env:
            - name: SERVICE_PORT
              value: {{ .Values.exporters.jmx.port | quote }}
            {{- with .Values.exporters.jmx.env }}
            {{- range $key, $value := . }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          resources:
          {{ toYaml .Values.exporters.jmx.resources | indent 12 }}
          volumeMounts:
            - name: config-jmx-exporter
              mountPath: /opt/jmx_exporter/config.yml
              subPath: config.yml
      {{- end }}

      {{- with .Values.presto.coordinator.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.presto.coordinator.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.presto.coordinator.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
