apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "presto.coordinator" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
spec:
  selector:
    matchLabels:
      app: {{ template "presto.name" . }}
      release: {{ .Release.Name }}
      component: coordinator
  template:
    metadata:
      labels:
        app: {{ template "presto.name" . }}
        release: {{ .Release.Name }}
        component: coordinator
    spec:
      {{- with .Values.image.securityContext }}
      securityContext:
        runAsUser: {{ .runAsUser }}
        runAsGroup: {{ .runAsGroup }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "presto.coordinator" . }}
        - name: connectors-config-volume
          configMap:
            name: {{ template "presto.connectors" . }}
      containers:
        - name: {{ .Chart.Name }}-coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.presto.coordinator.config.path }}
              name: config-volume
            - mountPath: {{ .Values.presto.coordinator.config.path }}/catalog
              name: connectors-config-volume
          ports:
            - name: http-coord
              containerPort: {{ .Values.presto.coordinator.config.server.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /ui/login.html
              port: http-coord
          readinessProbe:
            httpGet:
              path: /ui/login.html
              port: http-coord
          resources:
      {{- toYaml .Values.presto.coordinator.resources | nindent 12 }}
      {{- with .Values.presto.coordinator.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.presto.coordinator.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.presto.coordinator.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
