apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "presto.worker" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: worker
spec:
  replicas: {{ .Values.presto.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "presto.name" . }}
      release: {{ .Release.Name }}
      component: worker
  template:
    metadata:
      labels:
        app: {{ template "presto.name" . }}
        release: {{ .Release.Name }}
        component: worker
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "presto.worker" . }}
        - name: connectors-config-volume
          configMap:
            name: {{ template "presto.connectors" . }}
        - name: config-jmx-exporter
          configMap:
            name: {{ template "presto.jmx-exporter" . }}

      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.presto.worker.config.path }}
              name: config-volume
            - mountPath: {{ .Values.presto.worker.config.path }}/catalog
              name: connectors-config-volume
          ports:
            - name: http-worker
              containerPort: {{ .Values.presto.worker.config.server.port }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /v1/info/state
              port: http-worker
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - {{ .Values.presto.worker.config.path }}/health_check.sh
            initialDelaySeconds: 30
            periodSeconds: 5

          {{ if .Values.presto.worker.config.gracefulShutdown.enabled }}
          lifecycle:
            preStop:
              exec:
                command: [
                    "sh", "-c",
                    "curl -v  -H \"X-Presto-User: admin\" -X PUT -d '\"SHUTTING_DOWN\"' -H \"Content-type: application/json\" http://localhost:8080/v1/info/state && sleep {{ .Values.presto.worker.config.gracefulShutdown.gracePeriodSeconds }}"
                ]
          {{end }}
          resources:
        {{- toYaml .Values.presto.worker.resources | nindent 12 }}


        {{ if .Values.exporters.jmx.enabled }}
        - name: jmx-exporter
          image: "{{ .Values.exporters.jmx.image.repository }}:{{ .Values.exporters.jmx.image.tag }}"
          imagePullPolicy: {{ .Values.exporters.jmx.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.exporters.jmx.port }}
              protocol: TCP
              name: exporter
          livenessProbe:
            httpGet:
              path: /metrics
              port: exporter
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 60
            failureThreshold: 8
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /metrics
              port: exporter
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 60
            failureThreshold: 8
            successThreshold: 1
          env:
            - name: SERVICE_PORT
              value: {{ .Values.exporters.jmx.port | quote }}
            {{- with .Values.exporters.jmx.env }}
            {{- range $key, $value := . }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          resources:
          {{ toYaml .Values.exporters.jmx.resources | indent 12 }}
          volumeMounts:
            - name: config-jmx-exporter
              mountPath: /opt/jmx_exporter/config.yml
              subPath: config.yml
      {{- end }}

      {{- with .Values.presto.worker.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.presto.worker.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.presto.worker.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
