{{ if .Values.exporters.jmx.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "presto.fullname" . }}
  labels:
  {{- include "presto.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "presto.name" . }}
      monitoring.service: jmx
      release: {{ .Release.Name }}
      chart: {{ template "presto.chart" . }}
  endpoints:
    - port: exporter
      path: /metrics
      interval: 10s
{{ end }}
---
