apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{include "presto-loadbalancer.fullname" .}}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - namespaces
    verbs:
      - get
      - watch
      - list