apiVersion: v1
kind: Service
metadata:
  name: {{ include "presto-loadbalancer.fullname" . }}
  labels:
    {{- include "presto-loadbalancer.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "presto-loadbalancer.selectorLabels" . | nindent 4 }}
